markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Prabu Weerasinghe
url: http://pwee167.com
description: My rants and guides.
twitter: pwee167
