markdown: kramdown
permalink: /posts/:title/
highlighter: pygments
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Prabu Weerasinghe
url: http://pwee167.github.io
description: Rants and guides by Prabu Weerasinghe.
twitter: pwee167
