markdown: rdiscount
permalink: /posts/:title/
highlighter: true
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: PWEE167
url: http://pwee167.com
description: Rants and guides by Prabu Weerasinghe.
twitter: pwee167
