markdown: rdiscount
permalink: /posts/:title/
highlighter: true
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Prabu Weerasinghe
url: http://pwee167.com
description: My rants and guides.
twitter: pwee167
